#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Mon Dec 24 07:22:48 2018

MIT PS1 HW

@author: BlackBox
"""
import math
import sys

#Part A
def partA(annualSalary=120000,percentSaved=.1,cost=1000000):
    #annualSalary = float(input('Annual Salary: '))
    #percentSaved = float(input('Percent Saved in Decimal: '))
    #cost = float(input('Enter cost of home: '))
    currentSavings = 0
    months = 1
    downPayment = cost * .25
    while (currentSavings < downPayment):
        currentSavings += ((annualSalary / 12) * percentSaved)
        currentSavings += ((currentSavings*.04)/12)
        months += 1
    print('Number of months: {}'.format(months))
    
def partB(annualSalary=120000,percentSaved=.05,cost=500000,raisePercent=.03):
    #annualSalary = float(input('Annual Salary: '))
    #percentSaved = float(input('Percent Saved in Decimal: '))
    #cost = float(input('Enter cost of home: '))
    #raisePercent = float(input('Percent semiannual raise in Decimal '))
    currentSavings = 0
    months = 0
    downPayment = cost * .25
    while (currentSavings < downPayment):
        months += 1
        currentSavings += ((currentSavings*.04)/12)
        currentSavings += ((annualSalary / 12) * percentSaved)
        if ((months+1) % 6) == True:
            annualSalary = annualSalary + (annualSalary * raisePercent)
    print('Number of months: {}'.format((months)))

def partC(annualSalary=120000,percentSaved=.05,cost=500000,raisePercent=.03):
    #annualSalary = float(input('Annual Salary: '))
    #percentSaved = float(input('Percent Saved in Decimal: '))
    #cost = float(input('Enter cost of home: '))
    #raisePercent = float(input('Percent semiannual raise in Decimal '))
    currentSavings = 0
    months = 0
    downPayment = cost * .25
    while (currentSavings < downPayment):
        months += 1
        currentSavings += ((currentSavings*.04)/12)
        currentSavings += ((annualSalary / 12) * percentSaved)
        if ((months+1) % 6) == True:
            annualSalary = annualSalary + (annualSalary * raisePercent)
    print('Number of months: {}'.format((months)))